language: python
python:
- '3.6'

services:
- docker

branches:
  only:
  - master
  # tag format -> v.0.0.0
  - /^v.*$/

before_install:
  # cancel build if release not tagged
  # - if [ ! -n "$TRAVIS_TAG" ]; then exit 0; fi

  # prepare qemu
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

  # destination for compiled packages
  - mkdir ~/pypi_packages
  
  # build raspberry pi images
  - docker build -t armv6l -f docker/armv6l.dockerfile .
  - docker build -t armv7l -f docker/armv7l.dockerfile .

  # start images to compile pypi packages
  - docker run -v ~/pypi_packages:/volume armv6l
  - docker run -v ~/pypi_packages:/volume armv7l

install:
  # - pip install -U twine

# upload all pypi packages
script:
  - ls ~/pypi_packages
  # - twine upload --skip-existing ~/pypi_packages/*